#!/usr/bin/env python3
"""Author the Hair + Motion component libraries (data/art/hair/, data/art/motion/)
and the matching Drakness base-set cards (data/art/base-set/drakness/{hair,motion}/).

Existing variants are transcribed faithfully from the hand-crafted
prompts/Drakness/{hair,motion}/*.txt files (sourceVariant traces each one). A handful
of near-identical duplicates are consolidated (noted per entry). New entries add
popular fashion hairstyles / glamour-shot motion poses not in the original set.

Idempotent: re-running overwrites with the same content (no drift).
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
HERO_SLUG = "drakness"
HERO_ART = f"data/art/heroes/{HERO_SLUG}-thorne.json"

# ---------------------------------------------------------------------------
# HAIR — family -> list of (slug, name, a_pose_style, breeze, hair_change, extras, source)
# ---------------------------------------------------------------------------
HAIR = {
    "down": [
        ("center-part-wavy", None, None, None, None, None, None),  # already authored; skip
        ("natural", "Natural (no restyle)",
         "left natural, loose and relaxed",
         "No breeze.", "Hair is natural.", [],
         "Drakness_Qwen_Hair_Natural"),
        ("nearly-straight", "Nearly Straight, Same Length",
         "nearly straight, hanging beside the breasts, same length throughout",
         "No breeze.", "Hair is nearly-straight, hanging beside breasts, same length.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight"),
        ("semi-to-curly", "Semi-Straight to Curly",
         "semi-straight through the upper length, turning soft and curly toward the ends",
         "No breeze.", "Hair is semi-straight until middle of breasts, then curly and hanging beside breasts.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Semi"),
        ("drifting-back", "Drifting Back",
         "drifting backward on both sides with a slight swirl, as if caught mid-breeze",
         "Breeze blowing towards her.", "Hair is drifting backwards, equally on both sides, slight swirls.",
         ["Shoulders exposed."], "Drakness_Qwen_Hair_Flowing"),
        ("wild-tossed", "Wild Tossed",
         "tossed wildly to one side, parted above the ear, full of movement",
         "Moderate breeze towards her.",
         "Hair parted just above left ear, tossed wildly from left over top. Hair blowing wildly left and right.",
         [], "Drakness_Qwen_Hair_Wild"),
        # --- new additions (popular fashion) ---
        ("beach-waves", "Beach Waves",
         "falling in soft, tousled beach waves with a relaxed, lived-in texture",
         "Light breeze drifting over her shoulders.",
         "Hair falls in soft, tousled beach waves, loosely tumbling past the shoulders with a relaxed, lived-in texture.",
         [], None),
        ("half-up-half-down", "Half-Up, Half-Down",
         "half gathered back at the crown, the rest left down in soft waves",
         "Minimal breeze.",
         "The top half is gathered back and secured, the rest left down in soft waves cascading past the shoulders.",
         [], None),
        ("wet-look-slicked-back", "Wet-Look Slicked Back",
         "sleek and wet-look, slicked straight back off the face with a high-shine finish",
         "No breeze.",
         "Hair is sleek and wet-look, slicked straight back off the face with a high-shine, polished finish.",
         [], None),
        ("finger-waves-retro", "Retro Finger Waves",
         "set in classic finger waves, close to the head with smooth, defined ridges",
         "No breeze.",
         "Hair is styled in classic finger waves, a retro glamour set close to the head with smooth, defined ridges.",
         [], None),
        ("voluminous-blowout", "Voluminous Blowout",
         "a big, bouncy, glossy supermodel blowout, full volume from the roots",
         "Light breeze.",
         "Hair is styled in a voluminous, glossy blowout - big, bouncy body from the roots with a smooth, polished shine.",
         [], None),
        ("hollywood-glam-waves", "Old Hollywood Glam Waves",
         "set in deep, glossy old-Hollywood waves, swept to one side",
         "No breeze.",
         "Hair is set in deep, glossy old-Hollywood glamour waves, swept to one side with soft, rounded curls.",
         [], None),
        ("sleek-side-part", "Sleek Side Part",
         "sleek and straight with a deep side part",
         "No breeze.",
         "Hair is sleek and straight with a deep side part, smooth and glass-like with a glossy finish.",
         [], None),
        ("loose-glamour-curls", "Loose Glamour Curls",
         "soft, cascading curls with a polished, glamorous finish",
         "Light breeze.",
         "Hair falls in soft, cascading curls, polished and glamorous rather than tousled, with a healthy shine.",
         [], None),
    ],
    "framed": [
        ("below-clavicles-framed", "Framed, Below Clavicles",
         "sleek and semi-straight, length below the clavicles, sides cut tapered with tendrils framing her face",
         "Very slight breeze blowing at her.",
         "Hairstyle is sleek and semi-straight, hair length below clavicles, sides cut tapered tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Short"),
        ("top-of-breasts-framed", "Framed, Top of Breasts",
         "sleek and semi-straight, length to the top of the breasts, sides cut tapered with tendrils framing her face",
         "No breeze.",
         "Hairstyle is sleek and semi-straight, hair length to top of breasts with sides cut tapered tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Short_00002"),
        ("bottom-of-breasts-framed", "Framed, Bottom of Breasts",
         "sleek and semi-straight, length to the bottom of the breasts, sides cut tapered with tendrils framing her face",
         "No breeze.",
         "Hairstyle is sleek and semi-straight, hair length to bottom of breasts with sides cut tapered tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Frame_Basic + Drakness_Qwen_Hair_Straight_Shoulders (consolidated, near-identical)"),
        ("sides-of-breasts-framed", "Framed, Sides of Breasts",
         "sleek and semi-straight, length to the sides of the breasts, sides cut tapered at the eyes with tendrils framing her face",
         "Very slight breeze flowing at her.",
         "Hairstyle is sleek and semi-straight, hair length to sides of breasts, sides cut tapered at eyes with tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Frame_Breasts"),
        ("biceps-length-framed", "Framed, Biceps Length",
         "sleek and semi-straight, length to the middle of the biceps, sides cut tapered at the eyes with tendrils framing her face",
         "Very slight breeze flowing at her.",
         "Hairstyle is sleek and semi-straight, hair length to middle of biceps, sides cut tapered at eyes with tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Frame"),
        ("very-bottom-tapered-framed", "Framed, Very Bottom Tapered",
         "sleek and semi-straight, length to the very bottom of the breasts, sides cut tapered at the cheeks with tendrils framing her face",
         "Very slight breeze flowing at her.",
         "Hairstyle is sleek and semi-straight, hair length to very bottom of breasts, sides cut tapered at cheeks with tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Tapered"),
        ("bangs-tapered", "Tapered Bangs",
         "sleek and semi-straight with bangs cut tapered at the cheeks, tendrils framing her face",
         "Very slight breeze flowing at her.",
         "Hairstyle is sleek and semi-straight, hair length to very bottom of breasts, bangs cut tapered at cheeks with tendrils framing her face, hair contours her body.",
         ["Bold décolletage."], "Drakness_Qwen_Hair_Straight_Bangs"),
        # --- new additions ---
        ("curtain-bangs-framed", "Curtain Bangs",
         "long, sleek layers with soft curtain bangs parted at the centre, framing both sides of her face",
         "Light breeze.",
         "Hairstyle is sleek, long layers with soft curtain bangs parted at the centre, framing both sides of her face.",
         [], None),
        ("layered-face-framing", "Layered Face-Framing",
         "long soft layers with face-framing pieces swept forward at the cheekbones",
         "Light breeze.",
         "Hairstyle has long, soft layers with face-framing pieces swept forward at the cheekbones, adding movement around the face.",
         [], None),
    ],
    "pulled-back": [
        ("center-pulled", "Center Pulled Back",
         "pin straight, pulled behind and resting in front of the shoulders",
         "No breeze.", "Hair is pin straight, pulled behind and hanging in front of shoulders.",
         ["Bold décolletage."],
         "Drakness_Qwen_Hair_Straight_Back + Drakness_Qwen_Hair_Straight_Back_00002 + Drakness_Qwen_Hair_Straight_Pulled (consolidated, near-identical trio)"),
        ("swept-left", "Swept Left",
         "parted just above the right ear and pulled over the top, blowing left, right ear exposed",
         "Minimal breeze flowing to left.",
         "Hair parted just above right ear, pulled from right over top. Hair blowing to the left. Right ear exposed.",
         [], "Drakness_Qwen_Hair_Left"),
        ("swept-right", "Swept Right",
         "pulled behind the left shoulder and over the top of the head to the right, blowing right, left ear exposed",
         "Minimal breeze flowing to right.",
         "Hair pulled back behind her left shoulder and over top of her head to the right. Hair blowing to the right. Left ear exposed.",
         [], "Drakness_Qwen_Hair_Right"),
        # --- new additions ---
        ("side-swept-over-shoulder", "Side-Swept Over Shoulder",
         "swept entirely to one side, draped forward over the shoulder in a glamorous sweep",
         "Light breeze.",
         "Hair is swept entirely to one side, draped forward over the shoulder in a glamorous red-carpet sweep.",
         [], None),
        ("sleek-middle-part-tucked", "Sleek Middle Part, Tucked",
         "sleek with a precise middle part, tucked smoothly behind both ears",
         "No breeze.",
         "Hair is sleek with a precise middle part, tucked smoothly behind both ears.",
         [], None),
        ("low-ponytail-sleek", "Sleek Low Ponytail",
         "swept back into a sleek, low ponytail at the nape of the neck",
         "No breeze.",
         "Hair is swept back into a sleek, low ponytail gathered at the nape of the neck, smooth and glossy.",
         [], None),
        ("wrapped-ponytail", "Wrapped Ponytail",
         "a polished ponytail with a strand wrapped neatly around the base",
         "Light breeze.",
         "Hair is gathered into a ponytail with a thin strand wrapped neatly around the base, hiding the elastic.",
         [], None),
        # --- ponytail plain/tendril twins: same base style, pick per-shot/per-hero ---
        ("low-ponytail-loose-tendrils", "Low Ponytail with Loose Tendrils",
         "swept back into a sleek, low ponytail at the nape with a few long tendrils left loose to frame the temples and cheekbones",
         "Light breeze.",
         "Hair is swept back into a sleek, low ponytail gathered at the nape of the neck, with a few long tendrils deliberately left loose to frame the temples and cheekbones, seductive and exotic.",
         [], None),
        ("high-ponytail-sleek", "Sleek High Ponytail",
         "gathered into a high, sleek ponytail at the crown, smooth and polished with no loose strands",
         "Light breeze.",
         "Hair is gathered into a high, sleek ponytail at the crown, smooth and polished with every strand pulled back cleanly.",
         [], None),
        ("high-ponytail-loose-tendrils", "High Ponytail with Loose Tendrils",
         "gathered into a high, sleek ponytail with a few long tendrils left loose to frame the temples and cheekbones",
         "Light breeze.",
         "Hair is gathered into a high, sleek ponytail, with a few long tendrils deliberately left loose to frame the temples and cheekbones, seductive and exotic.",
         [], None),
    ],
    "updo": [
        ("pony-tail", None, None, None, None, None, None),  # already authored; skip
        ("high-bun", "High Bun",
         "swept up into a sleek high bun at the crown, smooth and polished",
         "No breeze.", "Hair is swept up into a sleek high bun at the crown, smooth and polished.",
         [], None),
        ("sleek-low-bun", "Sleek Low Bun",
         "gathered into a sleek, low chignon bun at the nape of the neck, smooth and refined",
         "No breeze.", "Hair is gathered into a sleek, low chignon bun at the nape of the neck, smooth and refined.",
         [], None),
        ("space-buns", "Space Buns",
         "parted down the middle and styled into two symmetrical space buns",
         "No breeze.", "Hair is parted down the middle and styled into two symmetrical space buns, playful and trendy.",
         [], None),
        ("loose-romantic-bun", "Loose Romantic Bun",
         "a soft, loose bun with face-framing tendrils, romantic and undone",
         "No breeze.",
         "Hair is gathered into a soft, loose bun with a few face-framing tendrils left loose, romantic and effortless.",
         [], None),
        ("twisted-half-up", "Twisted Half-Up",
         "the top section twisted back and secured, the rest left down",
         "Light breeze.",
         "The top section of hair is twisted back and secured at the crown, the rest left down in soft waves.",
         [], None),
        # --- new addition (exotic tendril look) ---
        ("high-bun-trailing-tendrils", "High Bun with Trailing Tendrils",
         "swept up into a high bun with several long, loose tendrils escaping to trail along the neck and temples",
         "Very light breeze.",
         "Hair is swept up into a high bun, with several long, loose tendrils deliberately left loose to trail along the neck and temples, an exotic, alluring fantasy-glamour look.",
         [], None),
    ],
    "braided": [
        ("fishtail-braid", "Fishtail Braid",
         "styled in a loose fishtail braid cascading over one shoulder, soft tendrils framing the face",
         "No breeze.", "Hair is styled in a loose fishtail braid cascading over one shoulder, soft tendrils framing the face.",
         [], None),
        ("braided-crown", "Braided Crown",
         "woven into a delicate braided crown encircling the head, the length left flowing beneath it",
         "No breeze.", "Hair is woven into a delicate braided crown encircling the head, with the length left flowing beneath it.",
         [], None),
        ("side-braid", "Loose Side Braid",
         "gathered into a single loose side braid draped over one shoulder",
         "No breeze.", "Hair is gathered into a single loose side braid draped over one shoulder.",
         [], None),
        # --- new addition (exotic tendril look) ---
        ("braided-updo-loose-tendrils", "Braided Updo with Loose Tendrils",
         "an elaborate braided updo at the crown, with wispy tendrils left loose at the temples and nape",
         "Very light breeze.",
         "Hair is woven into an elaborate braided updo at the crown, with wispy tendrils deliberately left loose at the temples and nape, an exotic, alluring fantasy-glamour look.",
         [], None),
    ],
}

# ---------------------------------------------------------------------------
# MOTION — family -> list of (slug, name, editorial, breeze, body, head, gaze,
#                             expression, pose, extras, source)
# ---------------------------------------------------------------------------
MOTION = {
    "standing": [
        ("three-quarter-glamour", "Classic 3/4 Glamour Stance",
         "A candid high-fashion editorial shot, dynamic natural movement, confident contrapposto posing.",
         "Light breeze.",
         "angled about 45 degrees to the camera (3/4 turn), weight on the back leg, hips and shoulders counter-rotated into a soft S-curve.",
         "turned back toward the camera, chin slightly down.", "eyes to camera.",
         "alluring, confident; lips slightly parted; expressive, sultry brows.",
         "one foot forward and lightly crossed; a hand resting at the hip, the other relaxed; poised mid-motion.",
         [], "Drakness_Qwen_Motion_ThreeQuarter"),
        ("side-profile-elegant", "Elegant Side Profile",
         "A candid high-fashion editorial shot, elegant glamour posing.",
         "Light breeze.",
         "full side profile to the camera, long neck, shoulders back, chest lifted.",
         "in profile, chin lifted.", "off-camera into the distance.",
         "composed, serene; lips softly together; expressive, sultry brows.",
         "one foot forward for an elegant line; arms relaxed with a graceful hand.",
         [], "Drakness_Qwen_Motion_Profile"),
        ("over-the-shoulder-glance", "Over-the-Shoulder Glance",
         "A candid high-fashion editorial shot, dynamic natural movement, confident glamour posing.",
         "Light breeze.",
         "3/4 back to the camera, weight shifted onto one leg, spine gently curved, showing the line of the back.",
         "turned over the shoulder toward the camera, chin slightly down.", "eyes to camera.",
         "alluring, confident; lips slightly parted; expressive, sultry brows.",
         "one hand at the hip, the other relaxed; glancing back over the shoulder, mid-motion.",
         [], "Drakness_Qwen_Motion_OverShoulder"),
        ("unpredictable-seductive", "Unpredictable Seductive Pose",
         "A candid high-fashion editorial shot, dynamic natural movement, expressive glamour pose, asymmetrical body language, fluid spontaneous, low-energy, seductive body positions.",
         "Random slight breeze.",
         "chest facing an unpredictable direction, hips shifting in unpredictable directions, shoulders pivoting unpredictably, legs spread apart in an elegant pose position.",
         "following the body's unpredictable shift.", "seductive, unpredictable.",
         "seductive and unpredictable; lips lush and active, non-neutral.",
         "hands in unpredictable positions, touching her body.",
         [], "Drakness_Qwen_Motion_Pose"),
        # --- new additions ---
        ("hand-on-hip-power", "Hand-on-Hip Power Pose",
         "A candid high-fashion editorial shot, confident power stance.",
         "Light breeze.",
         "standing tall, weight on one leg, shoulders squared to the camera.",
         "level, facing the camera directly.", "direct, confident eyes to camera.",
         "bold, confident, a hint of a smirk.",
         "one hand firmly on the hip, elbow out; the other arm relaxed at her side.",
         [], None),
        ("seated-elegant", "Seated Elegant Glamour",
         "A candid high-fashion editorial shot, refined seated glamour.",
         "No breeze.",
         "seated elegantly, legs crossed at the knee, spine long and upright.",
         "tilted slightly, chin level.", "to camera.",
         "composed, alluring half-smile.",
         "one hand resting on the knee, the other draped gracefully at her side.",
         [], None),
    ],
    "walking": [
        ("catwalk-confident", "Confident Catwalk Walk",
         "A candid high-fashion editorial shot, dynamic natural movement, expressive glamour pose, mid-motion, asymmetrical body language, fluid spontaneous glamour posing, mild-energy fashion photography.",
         "Breeze flowing any direction.",
         "walking towards the camera, body position adjusting with the stride.",
         "facing forward, matching the walk.", "remains focused on camera.",
         "alluring, confident smile, lips slightly parted; lips full and expressive.",
         "hips and shoulders positioned for the step; arms swinging with the walk; one foot stepping forward more.",
         [], "Drakness_Qwen_Motion_Catwalk"),
        ("high-energy-stride", "High-Energy Stride",
         "Candid high-fashion editorial shot, dynamic fluid movement, unposed seductive glamour photography, mid-motion, asymmetrical stance, shifted weight, non-rigid posture, full body in motion, high energy.",
         "Strong breeze flowing any direction.",
         "angled 3/4 to the camera, mid-stride, having a great time.",
         "turned to a 3/4 angle, chin up; neck and shoulders follow the turn.", "bright and engaged with the camera.",
         "a bright, confident smile with a hint of teeth; lips full and expressive.",
         "arms swinging with the energy of the stride.",
         [], "Drakness_Qwen_Motion_High"),
        # --- new addition ---
        ("strut-runway", "Bold Runway Strut",
         "A candid high-fashion editorial shot, bold runway strut, powerful stride.",
         "Breeze flowing any direction.",
         "striding forward with purpose, hips rolling with each step, shoulders back.",
         "level, facing forward.", "fixed ahead, confident.",
         "fierce, focused, lips softly together.",
         "arms swinging in rhythm with the stride; one foot placed directly in front of the other.",
         [], None),
        ("slow-sensual-walk", "Slow Sensual Walk",
         "A candid high-fashion editorial shot, slow sensual movement, deliberate pacing.",
         "Light breeze.",
         "walking slowly and deliberately towards the camera, hips swaying prominently with each step.",
         "level, chin slightly lowered, facing the camera.", "sultry, half-lidded gaze to camera.",
         "sultry, composed, lips softly together.",
         "arms relaxed and barely moving, weight settling into each slow step.",
         [], None),
        ("walking-away-glance-back", "Walking Away, Glance Back",
         "A candid high-fashion editorial shot, walking away with a glance back, classic editorial moment.",
         "Light breeze.",
         "walking away from the camera, weight shifting with the stride, back and shoulders in view.",
         "turned back over the shoulder toward the camera, mid-stride.", "glancing back to camera.",
         "alluring, a soft knowing smile.",
         "one hand trailing lightly at her side, caught mid-step as she glances back.",
         [], None),
        ("relaxed-stroll", "Relaxed Stroll",
         "A candid high-fashion editorial shot, relaxed casual stroll, soft natural movement.",
         "Light breeze.",
         "strolling casually, body relaxed and unposed, weight shifting naturally with each step.",
         "level, relaxed, facing forward.", "soft, easy gaze to camera.",
         "relaxed, natural smile.",
         "arms swinging loosely and naturally with the stroll.",
         [], None),
    ],
    "dynamic": [
        ("arching-twist", "Arching Twist",
         "A candid high-fashion editorial shot, dynamic natural movement, expressive glamour pose, mid-motion, asymmetrical body language, fluid spontaneous glamour posing, mild-energy fashion photography.",
         "Very light breeze flowing at her.",
         "entire body shifting and twisting, centre of gravity pronounced, breaking stiff vertical lines with organic body language; chest facing the camera at a slight angle and leaning forward; back arching; hips swayed; both feet on the ground, one foot far forward angled towards camera, one heel slightly raised.",
         "following the twist of the body.", "an inviting gaze.",
         "alluring, confident, unpredictable; lips full and expressive, slightly parted.",
         "one hand placed on her hip, the other in an elegant, alluring gesture away from her body.",
         [], "Drakness_Qwen_Motion_Arching"),
        ("fluid-floor-reach", "Fluid Floor Reach",
         "Candid high-fashion editorial photography, dynamic fluid movement, unposed seductive glamour, mid-motion, glamour stance, shifted weight, non-rigid posture, full body in motion, high fluid energy.",
         "Breeze flowing any direction.",
         "twisting through a 3/4 turn toward the camera; one knee bending, one leg straddled to the side.",
         "turned over the shoulder toward the camera.", "tracking the viewer.",
         "dynamic, intensely expressive, caught in a seductive emotional shift; features alternating between a playful, alluring grin and a seductive smile; lips active and non-neutral, brow line happy.",
         "one hand touches the ground, the other touches her body.",
         [], "Drakness_Qwen_Motion_Fluid"),
        ("mild-energy-touch", "Mild-Energy Touch",
         "A candid high-fashion editorial shot, dynamic natural movement, expressive glamour pose, mid-motion, asymmetrical body language, fluid spontaneous glamour posing, mild-energy fashion photography.",
         "Random slight breeze.",
         "legs in full-motion, only the toes of her shoes touching the ground.",
         "tilted and turned to a soft 3/4, chin slightly down.", "seductive, unpredictable.",
         "seductive and unpredictable; lips full and expressive, slightly parted.",
         "hands in unpredictable positions touching her body.",
         [], "Drakness_Qwen_Motion_Mild"),
        # --- new additions ---
        ("hair-flip-toss", "Hair Flip / Toss",
         "A candid high-fashion editorial shot, dynamic motion-capture moment.",
         "Strong gust, mid-toss.",
         "caught mid-motion as her hair whips through the air.",
         "thrown back slightly with the toss.", "eyes closed or just reopening, mid-movement.",
         "playful, exhilarated, lips parted.",
         "one hand lifted near the hair, body leaning into the motion.",
         [], None),
        ("twirl-spin", "Twirl / Spin",
         "A candid high-fashion editorial shot, dynamic spinning motion, fabric and hair in flow.",
         "Motion-generated breeze, swirling around her.",
         "captured mid-twirl, torso rotating, skirt or drape flaring outward.",
         "turned with the spin, following the motion.", "bright, joyful, glancing toward the camera.",
         "joyful, carefree, laughing smile.",
         "arms extended slightly for balance, caught mid-spin.",
         [], None),
        ("kneeling-glamour", "Kneeling Glamour Pose",
         "A candid high-fashion editorial shot, low dynamic glamour pose.",
         "No breeze.",
         "lowered into a graceful kneeling pose, one knee down, the other leg bent with foot planted.",
         "level, facing the camera.", "direct, alluring eyes to camera.",
         "sultry, composed half-smile.",
         "one hand resting on the raised knee, the other braced lightly on the ground.",
         [], None),
    ],
    "romantic": [
        ("blowing-kiss-full-body", "Blowing a Kiss (Full Body)",
         "Candid high-fashion editorial shot, dynamic natural movement, expressive glamour pose, mid-motion, asymmetrical body language, fluid spontaneous, mild-energy, body in all positions.",
         "No breeze.",
         "full head-to-toe shot, feet placed on the floor in glamour positions, legs exposed.",
         "position varies.", "remains focused on camera.",
         "glamorous, confident.",
         "one hand blowing a kiss, the other in an elegant, alluring gesture.",
         ["Bold décolletage.", "Straight hair, same length, behind her shoulders.", "Bright Red lipstick (override)."],
         "Drakness_Qwen_Motion_Kiss"),
        ("blowing-kiss-closeup", "Blowing a Kiss (Close-Up)",
         "Candid high-fashion editorial shot, dynamic natural movement, expressive glamour pose, mid-motion, asymmetrical body language, fluid spontaneous, mild-energy, body in all positions.",
         "No breeze.",
         "close-up shot from thighs to head, legs exposed.",
         "position varies.", "remains focused on camera.",
         "glamorous, confident.",
         "one hand blowing a kiss, the other in an elegant, alluring gesture.",
         ["Bold décolletage.", "Straight hair, same length, behind her shoulders.", "Bright Red lipstick (override)."],
         "Drakness_Qwen_Motion_Kiss_CloseUp"),
        ("tender-embrace-self", "Tender Self-Embrace",
         "A candid high-fashion editorial shot, soft intimate romantic moment.",
         "No breeze.",
         "arms wrapped softly around herself, shoulders slightly drawn in, a tender, vulnerable stance.",
         "tilted gently downward, then lifting toward camera.", "soft, intimate gaze to camera.",
         "tender, soft, a gentle closed-mouth smile.",
         "hands resting gently on her own upper arms, in a soft self-embrace.",
         [], None),
        ("hand-to-collarbone", "Hand to Collarbone",
         "A candid high-fashion editorial shot, soft romantic portraiture.",
         "Light breeze.",
         "standing softly, weight settled on one leg, chest open toward camera.",
         "tilted slightly, chin soft.", "soft, romantic gaze to camera.",
         "soft, romantic, lips slightly parted.",
         "one hand resting gently at her collarbone, the other relaxed at her side.",
         [], None),
        ("windswept-dreamy", "Windswept Dreamy Moment",
         "A candid high-fashion editorial shot, dreamy romantic moment, wind-caught hair.",
         "Strong breeze flowing towards her.",
         "standing softly, head tilted back slightly, basking in the breeze.",
         "tilted back gently, eyes soft or closed.", "soft, dreamy, eyes closed or half-lidded.",
         "serene, dreamy, soft closed-mouth smile.",
         "arms relaxed at her sides, hair caught fully in the wind.",
         [], None),
        ("playful-wink", "Playful Wink",
         "A candid high-fashion editorial shot, flirty playful romantic energy.",
         "Light breeze.",
         "standing with a playful, relaxed posture, weight on one hip.",
         "tilted slightly, chin down, playful.", "a wink to camera.",
         "playful, flirty, a bright, mischievous smile.",
         "one hand near her chin or hair, caught in a playful gesture.",
         [], None),
        ("sultry-over-shoulder", "Sultry Over-the-Shoulder",
         "A candid high-fashion editorial shot, sultry intimate glamour moment.",
         "No breeze.",
         "back to the camera, weight shifted onto one leg, spine softly curved, back exposed.",
         "turned over the shoulder toward the camera, chin low.", "sultry, smouldering gaze to camera.",
         "sultry, lips softly parted.",
         "one hand trailing along her own shoulder or hip, caught mid-glance.",
         [], None),
    ],
}


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def label_of(slug):
    return "".join(w.capitalize() for w in slug.split("-"))


hair_written, motion_written = [], []

for family, entries in HAIR.items():
    for slug, name, a_pose, breeze, hair_change, extras, source in entries:
        if name is None:
            hair_written.append(f"hair/{family}/{slug}")  # already authored, skip
            continue
        comp = {
            "id": f"hair/{family}/{slug}",
            "kind": "hair",
            "name": name,
            "a_pose_style": a_pose,
            "breeze": breeze,
            "hair_change": hair_change,
            "extras": extras,
            "compatibleStages": ["pose", "hair"],
        }
        if source:
            comp["sourceVariant"] = source
        write_json(ROOT / f"data/art/hair/{family}/{slug}.json", comp)
        hair_written.append(f"hair/{family}/{slug}")

        card = {
            "artId": f"{HERO_SLUG}-hair-{slug}",
            "kind": "base-set",
            "stage": "hair",
            "heroArt": HERO_ART,
            "component": f"data/art/hair/{family}/{slug}.json",
            "template": "data/art/base-set/_templates/heroes/hair-human.txt",
            "output": f"prompts/art/base-set/Drakness/hair/{family}/Drakness_Hair_{label_of(family)}_{label_of(slug)}.txt",
            "denoise": "~0.4-0.6",
        }
        write_json(ROOT / f"data/art/base-set/{HERO_SLUG}/hair/{family}/{slug}.json", card)

for family, entries in MOTION.items():
    for slug, name, editorial, breeze, body, head, gaze, expression, pose, extras, source in entries:
        comp = {
            "id": f"motion/{family}/{slug}",
            "kind": "motion",
            "name": name,
            "editorial": editorial,
            "breeze": breeze,
            "body": body,
            "head": head,
            "gaze": gaze,
            "expression": expression,
            "pose": pose,
            "extras": extras,
            "compatibleStages": ["motion"],
        }
        if source:
            comp["sourceVariant"] = source
        write_json(ROOT / f"data/art/motion/{family}/{slug}.json", comp)
        motion_written.append(f"motion/{family}/{slug}")

        card = {
            "artId": f"{HERO_SLUG}-motion-{slug}",
            "kind": "base-set",
            "stage": "motion",
            "heroArt": HERO_ART,
            "component": f"data/art/motion/{family}/{slug}.json",
            "template": "data/art/base-set/_templates/heroes/motion-human.txt",
            "output": f"prompts/art/base-set/Drakness/motion/{family}/Drakness_Motion_{label_of(family)}_{label_of(slug)}.txt",
            "denoise": "~0.4-0.6",
        }
        write_json(ROOT / f"data/art/base-set/{HERO_SLUG}/motion/{family}/{slug}.json", card)

print(f"Hair components: {len(hair_written)} (incl. 2 already-authored); cards written for new ones")
print(f"Motion components: {len(motion_written)}; cards written")
